// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagegenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageGenerationJobDelete is the builder for deleting a ImageGenerationJob entity.
type ImageGenerationJobDelete struct {
	config
	hooks    []Hook
	mutation *ImageGenerationJobMutation
}

// Where appends a list predicates to the ImageGenerationJobDelete builder.
func (_d *ImageGenerationJobDelete) Where(ps ...predicate.ImageGenerationJob) *ImageGenerationJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ImageGenerationJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageGenerationJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ImageGenerationJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(imagegenerationjob.Table, sqlgraph.NewFieldSpec(imagegenerationjob.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ImageGenerationJobDeleteOne is the builder for deleting a single ImageGenerationJob entity.
type ImageGenerationJobDeleteOne struct {
	_d *ImageGenerationJobDelete
}

// Where appends a list predicates to the ImageGenerationJobDelete builder.
func (_d *ImageGenerationJobDeleteOne) Where(ps ...predicate.ImageGenerationJob) *ImageGenerationJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ImageGenerationJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{imagegenerationjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageGenerationJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
