// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagegenerationjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageGenerationJobUpdate is the builder for updating ImageGenerationJob entities.
type ImageGenerationJobUpdate struct {
	config
	hooks    []Hook
	mutation *ImageGenerationJobMutation
}

// Where appends a list predicates to the ImageGenerationJobUpdate builder.
func (_u *ImageGenerationJobUpdate) Where(ps ...predicate.ImageGenerationJob) *ImageGenerationJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageGenerationJobUpdate) SetUserID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableUserID(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageGenerationJobUpdate) AddUserID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ImageGenerationJobUpdate) ClearUserID() *ImageGenerationJobUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImageGenerationJobUpdate) SetAPIKeyID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableAPIKeyID(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImageGenerationJobUpdate) AddAPIKeyID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ImageGenerationJobUpdate) ClearAPIKeyID() *ImageGenerationJobUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ImageGenerationJobUpdate) SetGroupID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableGroupID(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ImageGenerationJobUpdate) AddGroupID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ImageGenerationJobUpdate) ClearGroupID() *ImageGenerationJobUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *ImageGenerationJobUpdate) SetSubscriptionID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableSubscriptionID(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *ImageGenerationJobUpdate) AddSubscriptionID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *ImageGenerationJobUpdate) ClearSubscriptionID() *ImageGenerationJobUpdate {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ImageGenerationJobUpdate) SetAccountID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableAccountID(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ImageGenerationJobUpdate) AddAccountID(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ImageGenerationJobUpdate) ClearAccountID() *ImageGenerationJobUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetBillingType sets the "billing_type" field.
func (_u *ImageGenerationJobUpdate) SetBillingType(v int8) *ImageGenerationJobUpdate {
	_u.mutation.ResetBillingType()
	_u.mutation.SetBillingType(v)
	return _u
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableBillingType(v *int8) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetBillingType(*v)
	}
	return _u
}

// AddBillingType adds value to the "billing_type" field.
func (_u *ImageGenerationJobUpdate) AddBillingType(v int8) *ImageGenerationJobUpdate {
	_u.mutation.AddBillingType(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ImageGenerationJobUpdate) SetSource(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableSource(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ImageGenerationJobUpdate) SetOperation(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableOperation(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageGenerationJobUpdate) SetStatus(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableStatus(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *ImageGenerationJobUpdate) SetPublicModel(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillablePublicModel(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *ImageGenerationJobUpdate) SetUpstreamModel(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableUpstreamModel(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *ImageGenerationJobUpdate) ClearUpstreamModel() *ImageGenerationJobUpdate {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetRequestedSize sets the "requested_size" field.
func (_u *ImageGenerationJobUpdate) SetRequestedSize(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetRequestedSize(v)
	return _u
}

// SetNillableRequestedSize sets the "requested_size" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableRequestedSize(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetRequestedSize(*v)
	}
	return _u
}

// ClearRequestedSize clears the value of the "requested_size" field.
func (_u *ImageGenerationJobUpdate) ClearRequestedSize() *ImageGenerationJobUpdate {
	_u.mutation.ClearRequestedSize()
	return _u
}

// SetActualSize sets the "actual_size" field.
func (_u *ImageGenerationJobUpdate) SetActualSize(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetActualSize(v)
	return _u
}

// SetNillableActualSize sets the "actual_size" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableActualSize(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetActualSize(*v)
	}
	return _u
}

// ClearActualSize clears the value of the "actual_size" field.
func (_u *ImageGenerationJobUpdate) ClearActualSize() *ImageGenerationJobUpdate {
	_u.mutation.ClearActualSize()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *ImageGenerationJobUpdate) SetQuality(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableQuality(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *ImageGenerationJobUpdate) ClearQuality() *ImageGenerationJobUpdate {
	_u.mutation.ClearQuality()
	return _u
}

// SetResponseFormat sets the "response_format" field.
func (_u *ImageGenerationJobUpdate) SetResponseFormat(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetResponseFormat(v)
	return _u
}

// SetNillableResponseFormat sets the "response_format" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableResponseFormat(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetResponseFormat(*v)
	}
	return _u
}

// ClearResponseFormat clears the value of the "response_format" field.
func (_u *ImageGenerationJobUpdate) ClearResponseFormat() *ImageGenerationJobUpdate {
	_u.mutation.ClearResponseFormat()
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *ImageGenerationJobUpdate) SetUpstreamTaskID(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableUpstreamTaskID(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *ImageGenerationJobUpdate) ClearUpstreamTaskID() *ImageGenerationJobUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ImageGenerationJobUpdate) SetIdempotencyKey(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableIdempotencyKey(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ImageGenerationJobUpdate) ClearIdempotencyKey() *ImageGenerationJobUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *ImageGenerationJobUpdate) SetRequestHash(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableRequestHash(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// ClearRequestHash clears the value of the "request_hash" field.
func (_u *ImageGenerationJobUpdate) ClearRequestHash() *ImageGenerationJobUpdate {
	_u.mutation.ClearRequestHash()
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *ImageGenerationJobUpdate) SetPromptHash(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillablePromptHash(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetPayloadObjectRef sets the "payload_object_ref" field.
func (_u *ImageGenerationJobUpdate) SetPayloadObjectRef(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetPayloadObjectRef(v)
	return _u
}

// SetNillablePayloadObjectRef sets the "payload_object_ref" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillablePayloadObjectRef(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetPayloadObjectRef(*v)
	}
	return _u
}

// ClearPayloadObjectRef clears the value of the "payload_object_ref" field.
func (_u *ImageGenerationJobUpdate) ClearPayloadObjectRef() *ImageGenerationJobUpdate {
	_u.mutation.ClearPayloadObjectRef()
	return _u
}

// SetResultObjectRefs sets the "result_object_refs" field.
func (_u *ImageGenerationJobUpdate) SetResultObjectRefs(v []string) *ImageGenerationJobUpdate {
	_u.mutation.SetResultObjectRefs(v)
	return _u
}

// AppendResultObjectRefs appends value to the "result_object_refs" field.
func (_u *ImageGenerationJobUpdate) AppendResultObjectRefs(v []string) *ImageGenerationJobUpdate {
	_u.mutation.AppendResultObjectRefs(v)
	return _u
}

// SetBaseCost sets the "base_cost" field.
func (_u *ImageGenerationJobUpdate) SetBaseCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.ResetBaseCost()
	_u.mutation.SetBaseCost(v)
	return _u
}

// SetNillableBaseCost sets the "base_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableBaseCost(v *float64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetBaseCost(*v)
	}
	return _u
}

// AddBaseCost adds value to the "base_cost" field.
func (_u *ImageGenerationJobUpdate) AddBaseCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.AddBaseCost(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *ImageGenerationJobUpdate) SetRateMultiplier(v float64) *ImageGenerationJobUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableRateMultiplier(v *float64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *ImageGenerationJobUpdate) AddRateMultiplier(v float64) *ImageGenerationJobUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *ImageGenerationJobUpdate) SetEstimatedCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableEstimatedCost(v *float64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *ImageGenerationJobUpdate) AddEstimatedCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetHeldCost sets the "held_cost" field.
func (_u *ImageGenerationJobUpdate) SetHeldCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.ResetHeldCost()
	_u.mutation.SetHeldCost(v)
	return _u
}

// SetNillableHeldCost sets the "held_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableHeldCost(v *float64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetHeldCost(*v)
	}
	return _u
}

// AddHeldCost adds value to the "held_cost" field.
func (_u *ImageGenerationJobUpdate) AddHeldCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.AddHeldCost(v)
	return _u
}

// SetSettledCost sets the "settled_cost" field.
func (_u *ImageGenerationJobUpdate) SetSettledCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.ResetSettledCost()
	_u.mutation.SetSettledCost(v)
	return _u
}

// SetNillableSettledCost sets the "settled_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableSettledCost(v *float64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetSettledCost(*v)
	}
	return _u
}

// AddSettledCost adds value to the "settled_cost" field.
func (_u *ImageGenerationJobUpdate) AddSettledCost(v float64) *ImageGenerationJobUpdate {
	_u.mutation.AddSettledCost(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ImageGenerationJobUpdate) SetErrorCode(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableErrorCode(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *ImageGenerationJobUpdate) ClearErrorCode() *ImageGenerationJobUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ImageGenerationJobUpdate) SetErrorMessage(v string) *ImageGenerationJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableErrorMessage(v *string) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ImageGenerationJobUpdate) ClearErrorMessage() *ImageGenerationJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ImageGenerationJobUpdate) SetAttemptCount(v int) *ImageGenerationJobUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableAttemptCount(v *int) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ImageGenerationJobUpdate) AddAttemptCount(v int) *ImageGenerationJobUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetClaimVersion sets the "claim_version" field.
func (_u *ImageGenerationJobUpdate) SetClaimVersion(v int64) *ImageGenerationJobUpdate {
	_u.mutation.ResetClaimVersion()
	_u.mutation.SetClaimVersion(v)
	return _u
}

// SetNillableClaimVersion sets the "claim_version" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableClaimVersion(v *int64) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetClaimVersion(*v)
	}
	return _u
}

// AddClaimVersion adds value to the "claim_version" field.
func (_u *ImageGenerationJobUpdate) AddClaimVersion(v int64) *ImageGenerationJobUpdate {
	_u.mutation.AddClaimVersion(v)
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *ImageGenerationJobUpdate) SetLeaseExpiresAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableLeaseExpiresAt(v *time.Time) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *ImageGenerationJobUpdate) ClearLeaseExpiresAt() *ImageGenerationJobUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *ImageGenerationJobUpdate) SetNextAttemptAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableNextAttemptAt(v *time.Time) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *ImageGenerationJobUpdate) ClearNextAttemptAt() *ImageGenerationJobUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageGenerationJobUpdate) SetUpdatedAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *ImageGenerationJobUpdate) SetSubmittedAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableSubmittedAt(v *time.Time) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *ImageGenerationJobUpdate) ClearSubmittedAt() *ImageGenerationJobUpdate {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ImageGenerationJobUpdate) SetCompletedAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableCompletedAt(v *time.Time) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ImageGenerationJobUpdate) ClearCompletedAt() *ImageGenerationJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ImageGenerationJobUpdate) SetSettledAt(v time.Time) *ImageGenerationJobUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdate) SetNillableSettledAt(v *time.Time) *ImageGenerationJobUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ImageGenerationJobUpdate) ClearSettledAt() *ImageGenerationJobUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the ImageGenerationJobMutation object of the builder.
func (_u *ImageGenerationJobUpdate) Mutation() *ImageGenerationJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageGenerationJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageGenerationJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageGenerationJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageGenerationJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageGenerationJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagegenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageGenerationJobUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := imagegenerationjob.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := imagegenerationjob.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imagegenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := imagegenerationjob.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := imagegenerationjob.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedSize(); ok {
		if err := imagegenerationjob.RequestedSizeValidator(v); err != nil {
			return &ValidationError{Name: "requested_size", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.requested_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualSize(); ok {
		if err := imagegenerationjob.ActualSizeValidator(v); err != nil {
			return &ValidationError{Name: "actual_size", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.actual_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := imagegenerationjob.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseFormat(); ok {
		if err := imagegenerationjob.ResponseFormatValidator(v); err != nil {
			return &ValidationError{Name: "response_format", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.response_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := imagegenerationjob.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := imagegenerationjob.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := imagegenerationjob.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := imagegenerationjob.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadObjectRef(); ok {
		if err := imagegenerationjob.PayloadObjectRefValidator(v); err != nil {
			return &ValidationError{Name: "payload_object_ref", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.payload_object_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := imagegenerationjob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageGenerationJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagegenerationjob.Table, imagegenerationjob.Columns, sqlgraph.NewFieldSpec(imagegenerationjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imagegenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imagegenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(imagegenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(imagegenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(imagegenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(imagegenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BillingType(); ok {
		_spec.SetField(imagegenerationjob.FieldBillingType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedBillingType(); ok {
		_spec.AddField(imagegenerationjob.FieldBillingType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(imagegenerationjob.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(imagegenerationjob.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagegenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(imagegenerationjob.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(imagegenerationjob.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(imagegenerationjob.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedSize(); ok {
		_spec.SetField(imagegenerationjob.FieldRequestedSize, field.TypeString, value)
	}
	if _u.mutation.RequestedSizeCleared() {
		_spec.ClearField(imagegenerationjob.FieldRequestedSize, field.TypeString)
	}
	if value, ok := _u.mutation.ActualSize(); ok {
		_spec.SetField(imagegenerationjob.FieldActualSize, field.TypeString, value)
	}
	if _u.mutation.ActualSizeCleared() {
		_spec.ClearField(imagegenerationjob.FieldActualSize, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(imagegenerationjob.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(imagegenerationjob.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseFormat(); ok {
		_spec.SetField(imagegenerationjob.FieldResponseFormat, field.TypeString, value)
	}
	if _u.mutation.ResponseFormatCleared() {
		_spec.ClearField(imagegenerationjob.FieldResponseFormat, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(imagegenerationjob.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(imagegenerationjob.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(imagegenerationjob.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(imagegenerationjob.FieldRequestHash, field.TypeString, value)
	}
	if _u.mutation.RequestHashCleared() {
		_spec.ClearField(imagegenerationjob.FieldRequestHash, field.TypeString)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(imagegenerationjob.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadObjectRef(); ok {
		_spec.SetField(imagegenerationjob.FieldPayloadObjectRef, field.TypeString, value)
	}
	if _u.mutation.PayloadObjectRefCleared() {
		_spec.ClearField(imagegenerationjob.FieldPayloadObjectRef, field.TypeString)
	}
	if value, ok := _u.mutation.ResultObjectRefs(); ok {
		_spec.SetField(imagegenerationjob.FieldResultObjectRefs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultObjectRefs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, imagegenerationjob.FieldResultObjectRefs, value)
		})
	}
	if value, ok := _u.mutation.BaseCost(); ok {
		_spec.SetField(imagegenerationjob.FieldBaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseCost(); ok {
		_spec.AddField(imagegenerationjob.FieldBaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(imagegenerationjob.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(imagegenerationjob.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(imagegenerationjob.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(imagegenerationjob.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HeldCost(); ok {
		_spec.SetField(imagegenerationjob.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeldCost(); ok {
		_spec.AddField(imagegenerationjob.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledCost(); ok {
		_spec.SetField(imagegenerationjob.FieldSettledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledCost(); ok {
		_spec.AddField(imagegenerationjob.FieldSettledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(imagegenerationjob.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(imagegenerationjob.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(imagegenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(imagegenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(imagegenerationjob.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(imagegenerationjob.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClaimVersion(); ok {
		_spec.SetField(imagegenerationjob.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimVersion(); ok {
		_spec.AddField(imagegenerationjob.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(imagegenerationjob.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(imagegenerationjob.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(imagegenerationjob.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldSettledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagegenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageGenerationJobUpdateOne is the builder for updating a single ImageGenerationJob entity.
type ImageGenerationJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageGenerationJobMutation
}

// SetUserID sets the "user_id" field.
func (_u *ImageGenerationJobUpdateOne) SetUserID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableUserID(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageGenerationJobUpdateOne) AddUserID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearUserID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImageGenerationJobUpdateOne) SetAPIKeyID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableAPIKeyID(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImageGenerationJobUpdateOne) AddAPIKeyID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearAPIKeyID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ImageGenerationJobUpdateOne) SetGroupID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableGroupID(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ImageGenerationJobUpdateOne) AddGroupID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearGroupID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *ImageGenerationJobUpdateOne) SetSubscriptionID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableSubscriptionID(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *ImageGenerationJobUpdateOne) AddSubscriptionID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// ClearSubscriptionID clears the value of the "subscription_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearSubscriptionID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearSubscriptionID()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ImageGenerationJobUpdateOne) SetAccountID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableAccountID(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ImageGenerationJobUpdateOne) AddAccountID(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearAccountID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetBillingType sets the "billing_type" field.
func (_u *ImageGenerationJobUpdateOne) SetBillingType(v int8) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetBillingType()
	_u.mutation.SetBillingType(v)
	return _u
}

// SetNillableBillingType sets the "billing_type" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableBillingType(v *int8) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetBillingType(*v)
	}
	return _u
}

// AddBillingType adds value to the "billing_type" field.
func (_u *ImageGenerationJobUpdateOne) AddBillingType(v int8) *ImageGenerationJobUpdateOne {
	_u.mutation.AddBillingType(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ImageGenerationJobUpdateOne) SetSource(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableSource(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetOperation sets the "operation" field.
func (_u *ImageGenerationJobUpdateOne) SetOperation(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableOperation(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageGenerationJobUpdateOne) SetStatus(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableStatus(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *ImageGenerationJobUpdateOne) SetPublicModel(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillablePublicModel(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *ImageGenerationJobUpdateOne) SetUpstreamModel(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableUpstreamModel(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *ImageGenerationJobUpdateOne) ClearUpstreamModel() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetRequestedSize sets the "requested_size" field.
func (_u *ImageGenerationJobUpdateOne) SetRequestedSize(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetRequestedSize(v)
	return _u
}

// SetNillableRequestedSize sets the "requested_size" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableRequestedSize(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetRequestedSize(*v)
	}
	return _u
}

// ClearRequestedSize clears the value of the "requested_size" field.
func (_u *ImageGenerationJobUpdateOne) ClearRequestedSize() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearRequestedSize()
	return _u
}

// SetActualSize sets the "actual_size" field.
func (_u *ImageGenerationJobUpdateOne) SetActualSize(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetActualSize(v)
	return _u
}

// SetNillableActualSize sets the "actual_size" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableActualSize(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetActualSize(*v)
	}
	return _u
}

// ClearActualSize clears the value of the "actual_size" field.
func (_u *ImageGenerationJobUpdateOne) ClearActualSize() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearActualSize()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *ImageGenerationJobUpdateOne) SetQuality(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableQuality(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *ImageGenerationJobUpdateOne) ClearQuality() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearQuality()
	return _u
}

// SetResponseFormat sets the "response_format" field.
func (_u *ImageGenerationJobUpdateOne) SetResponseFormat(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetResponseFormat(v)
	return _u
}

// SetNillableResponseFormat sets the "response_format" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableResponseFormat(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetResponseFormat(*v)
	}
	return _u
}

// ClearResponseFormat clears the value of the "response_format" field.
func (_u *ImageGenerationJobUpdateOne) ClearResponseFormat() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearResponseFormat()
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *ImageGenerationJobUpdateOne) SetUpstreamTaskID(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableUpstreamTaskID(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *ImageGenerationJobUpdateOne) ClearUpstreamTaskID() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ImageGenerationJobUpdateOne) SetIdempotencyKey(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableIdempotencyKey(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ImageGenerationJobUpdateOne) ClearIdempotencyKey() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetRequestHash sets the "request_hash" field.
func (_u *ImageGenerationJobUpdateOne) SetRequestHash(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetRequestHash(v)
	return _u
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableRequestHash(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetRequestHash(*v)
	}
	return _u
}

// ClearRequestHash clears the value of the "request_hash" field.
func (_u *ImageGenerationJobUpdateOne) ClearRequestHash() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearRequestHash()
	return _u
}

// SetPromptHash sets the "prompt_hash" field.
func (_u *ImageGenerationJobUpdateOne) SetPromptHash(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetPromptHash(v)
	return _u
}

// SetNillablePromptHash sets the "prompt_hash" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillablePromptHash(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetPromptHash(*v)
	}
	return _u
}

// SetPayloadObjectRef sets the "payload_object_ref" field.
func (_u *ImageGenerationJobUpdateOne) SetPayloadObjectRef(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetPayloadObjectRef(v)
	return _u
}

// SetNillablePayloadObjectRef sets the "payload_object_ref" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillablePayloadObjectRef(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetPayloadObjectRef(*v)
	}
	return _u
}

// ClearPayloadObjectRef clears the value of the "payload_object_ref" field.
func (_u *ImageGenerationJobUpdateOne) ClearPayloadObjectRef() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearPayloadObjectRef()
	return _u
}

// SetResultObjectRefs sets the "result_object_refs" field.
func (_u *ImageGenerationJobUpdateOne) SetResultObjectRefs(v []string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetResultObjectRefs(v)
	return _u
}

// AppendResultObjectRefs appends value to the "result_object_refs" field.
func (_u *ImageGenerationJobUpdateOne) AppendResultObjectRefs(v []string) *ImageGenerationJobUpdateOne {
	_u.mutation.AppendResultObjectRefs(v)
	return _u
}

// SetBaseCost sets the "base_cost" field.
func (_u *ImageGenerationJobUpdateOne) SetBaseCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetBaseCost()
	_u.mutation.SetBaseCost(v)
	return _u
}

// SetNillableBaseCost sets the "base_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableBaseCost(v *float64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetBaseCost(*v)
	}
	return _u
}

// AddBaseCost adds value to the "base_cost" field.
func (_u *ImageGenerationJobUpdateOne) AddBaseCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddBaseCost(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *ImageGenerationJobUpdateOne) SetRateMultiplier(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableRateMultiplier(v *float64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *ImageGenerationJobUpdateOne) AddRateMultiplier(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetEstimatedCost sets the "estimated_cost" field.
func (_u *ImageGenerationJobUpdateOne) SetEstimatedCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetEstimatedCost()
	_u.mutation.SetEstimatedCost(v)
	return _u
}

// SetNillableEstimatedCost sets the "estimated_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableEstimatedCost(v *float64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetEstimatedCost(*v)
	}
	return _u
}

// AddEstimatedCost adds value to the "estimated_cost" field.
func (_u *ImageGenerationJobUpdateOne) AddEstimatedCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddEstimatedCost(v)
	return _u
}

// SetHeldCost sets the "held_cost" field.
func (_u *ImageGenerationJobUpdateOne) SetHeldCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetHeldCost()
	_u.mutation.SetHeldCost(v)
	return _u
}

// SetNillableHeldCost sets the "held_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableHeldCost(v *float64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetHeldCost(*v)
	}
	return _u
}

// AddHeldCost adds value to the "held_cost" field.
func (_u *ImageGenerationJobUpdateOne) AddHeldCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddHeldCost(v)
	return _u
}

// SetSettledCost sets the "settled_cost" field.
func (_u *ImageGenerationJobUpdateOne) SetSettledCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetSettledCost()
	_u.mutation.SetSettledCost(v)
	return _u
}

// SetNillableSettledCost sets the "settled_cost" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableSettledCost(v *float64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetSettledCost(*v)
	}
	return _u
}

// AddSettledCost adds value to the "settled_cost" field.
func (_u *ImageGenerationJobUpdateOne) AddSettledCost(v float64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddSettledCost(v)
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ImageGenerationJobUpdateOne) SetErrorCode(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableErrorCode(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *ImageGenerationJobUpdateOne) ClearErrorCode() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ImageGenerationJobUpdateOne) SetErrorMessage(v string) *ImageGenerationJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableErrorMessage(v *string) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ImageGenerationJobUpdateOne) ClearErrorMessage() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *ImageGenerationJobUpdateOne) SetAttemptCount(v int) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableAttemptCount(v *int) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *ImageGenerationJobUpdateOne) AddAttemptCount(v int) *ImageGenerationJobUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetClaimVersion sets the "claim_version" field.
func (_u *ImageGenerationJobUpdateOne) SetClaimVersion(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.ResetClaimVersion()
	_u.mutation.SetClaimVersion(v)
	return _u
}

// SetNillableClaimVersion sets the "claim_version" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableClaimVersion(v *int64) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetClaimVersion(*v)
	}
	return _u
}

// AddClaimVersion adds value to the "claim_version" field.
func (_u *ImageGenerationJobUpdateOne) AddClaimVersion(v int64) *ImageGenerationJobUpdateOne {
	_u.mutation.AddClaimVersion(v)
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *ImageGenerationJobUpdateOne) SetLeaseExpiresAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *ImageGenerationJobUpdateOne) ClearLeaseExpiresAt() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *ImageGenerationJobUpdateOne) SetNextAttemptAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableNextAttemptAt(v *time.Time) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *ImageGenerationJobUpdateOne) ClearNextAttemptAt() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageGenerationJobUpdateOne) SetUpdatedAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *ImageGenerationJobUpdateOne) SetSubmittedAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableSubmittedAt(v *time.Time) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (_u *ImageGenerationJobUpdateOne) ClearSubmittedAt() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearSubmittedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ImageGenerationJobUpdateOne) SetCompletedAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableCompletedAt(v *time.Time) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ImageGenerationJobUpdateOne) ClearCompletedAt() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ImageGenerationJobUpdateOne) SetSettledAt(v time.Time) *ImageGenerationJobUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ImageGenerationJobUpdateOne) SetNillableSettledAt(v *time.Time) *ImageGenerationJobUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ImageGenerationJobUpdateOne) ClearSettledAt() *ImageGenerationJobUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the ImageGenerationJobMutation object of the builder.
func (_u *ImageGenerationJobUpdateOne) Mutation() *ImageGenerationJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageGenerationJobUpdate builder.
func (_u *ImageGenerationJobUpdateOne) Where(ps ...predicate.ImageGenerationJob) *ImageGenerationJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageGenerationJobUpdateOne) Select(field string, fields ...string) *ImageGenerationJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageGenerationJob entity.
func (_u *ImageGenerationJobUpdateOne) Save(ctx context.Context) (*ImageGenerationJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageGenerationJobUpdateOne) SaveX(ctx context.Context) *ImageGenerationJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageGenerationJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageGenerationJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageGenerationJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagegenerationjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageGenerationJobUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := imagegenerationjob.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operation(); ok {
		if err := imagegenerationjob.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imagegenerationjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := imagegenerationjob.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := imagegenerationjob.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedSize(); ok {
		if err := imagegenerationjob.RequestedSizeValidator(v); err != nil {
			return &ValidationError{Name: "requested_size", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.requested_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActualSize(); ok {
		if err := imagegenerationjob.ActualSizeValidator(v); err != nil {
			return &ValidationError{Name: "actual_size", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.actual_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := imagegenerationjob.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseFormat(); ok {
		if err := imagegenerationjob.ResponseFormatValidator(v); err != nil {
			return &ValidationError{Name: "response_format", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.response_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := imagegenerationjob.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := imagegenerationjob.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestHash(); ok {
		if err := imagegenerationjob.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.request_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromptHash(); ok {
		if err := imagegenerationjob.PromptHashValidator(v); err != nil {
			return &ValidationError{Name: "prompt_hash", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.prompt_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PayloadObjectRef(); ok {
		if err := imagegenerationjob.PayloadObjectRefValidator(v); err != nil {
			return &ValidationError{Name: "payload_object_ref", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.payload_object_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := imagegenerationjob.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGenerationJob.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageGenerationJobUpdateOne) sqlSave(ctx context.Context) (_node *ImageGenerationJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagegenerationjob.Table, imagegenerationjob.Columns, sqlgraph.NewFieldSpec(imagegenerationjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageGenerationJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagegenerationjob.FieldID)
		for _, f := range fields {
			if !imagegenerationjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagegenerationjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imagegenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imagegenerationjob.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(imagegenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(imagegenerationjob.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64, value)
	}
	if _u.mutation.SubscriptionIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldSubscriptionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(imagegenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(imagegenerationjob.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BillingType(); ok {
		_spec.SetField(imagegenerationjob.FieldBillingType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedBillingType(); ok {
		_spec.AddField(imagegenerationjob.FieldBillingType, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(imagegenerationjob.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(imagegenerationjob.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagegenerationjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(imagegenerationjob.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(imagegenerationjob.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(imagegenerationjob.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.RequestedSize(); ok {
		_spec.SetField(imagegenerationjob.FieldRequestedSize, field.TypeString, value)
	}
	if _u.mutation.RequestedSizeCleared() {
		_spec.ClearField(imagegenerationjob.FieldRequestedSize, field.TypeString)
	}
	if value, ok := _u.mutation.ActualSize(); ok {
		_spec.SetField(imagegenerationjob.FieldActualSize, field.TypeString, value)
	}
	if _u.mutation.ActualSizeCleared() {
		_spec.ClearField(imagegenerationjob.FieldActualSize, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(imagegenerationjob.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(imagegenerationjob.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseFormat(); ok {
		_spec.SetField(imagegenerationjob.FieldResponseFormat, field.TypeString, value)
	}
	if _u.mutation.ResponseFormatCleared() {
		_spec.ClearField(imagegenerationjob.FieldResponseFormat, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(imagegenerationjob.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(imagegenerationjob.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(imagegenerationjob.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(imagegenerationjob.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.RequestHash(); ok {
		_spec.SetField(imagegenerationjob.FieldRequestHash, field.TypeString, value)
	}
	if _u.mutation.RequestHashCleared() {
		_spec.ClearField(imagegenerationjob.FieldRequestHash, field.TypeString)
	}
	if value, ok := _u.mutation.PromptHash(); ok {
		_spec.SetField(imagegenerationjob.FieldPromptHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayloadObjectRef(); ok {
		_spec.SetField(imagegenerationjob.FieldPayloadObjectRef, field.TypeString, value)
	}
	if _u.mutation.PayloadObjectRefCleared() {
		_spec.ClearField(imagegenerationjob.FieldPayloadObjectRef, field.TypeString)
	}
	if value, ok := _u.mutation.ResultObjectRefs(); ok {
		_spec.SetField(imagegenerationjob.FieldResultObjectRefs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultObjectRefs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, imagegenerationjob.FieldResultObjectRefs, value)
		})
	}
	if value, ok := _u.mutation.BaseCost(); ok {
		_spec.SetField(imagegenerationjob.FieldBaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseCost(); ok {
		_spec.AddField(imagegenerationjob.FieldBaseCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(imagegenerationjob.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(imagegenerationjob.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EstimatedCost(); ok {
		_spec.SetField(imagegenerationjob.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedCost(); ok {
		_spec.AddField(imagegenerationjob.FieldEstimatedCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.HeldCost(); ok {
		_spec.SetField(imagegenerationjob.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeldCost(); ok {
		_spec.AddField(imagegenerationjob.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SettledCost(); ok {
		_spec.SetField(imagegenerationjob.FieldSettledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledCost(); ok {
		_spec.AddField(imagegenerationjob.FieldSettledCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(imagegenerationjob.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(imagegenerationjob.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(imagegenerationjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(imagegenerationjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(imagegenerationjob.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(imagegenerationjob.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClaimVersion(); ok {
		_spec.SetField(imagegenerationjob.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimVersion(); ok {
		_spec.AddField(imagegenerationjob.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(imagegenerationjob.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(imagegenerationjob.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldSubmittedAt, field.TypeTime, value)
	}
	if _u.mutation.SubmittedAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldSubmittedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(imagegenerationjob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(imagegenerationjob.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(imagegenerationjob.FieldSettledAt, field.TypeTime)
	}
	_node = &ImageGenerationJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagegenerationjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
