// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagegenerationjob"
)

// ImageGenerationJob is the model entity for the ImageGenerationJob schema.
type ImageGenerationJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType int8 `json:"billing_type,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Operation holds the value of the "operation" field.
	Operation string `json:"operation,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PublicModel holds the value of the "public_model" field.
	PublicModel string `json:"public_model,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName *string `json:"display_name,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel *string `json:"upstream_model,omitempty"`
	// RequestedSize holds the value of the "requested_size" field.
	RequestedSize *string `json:"requested_size,omitempty"`
	// ActualSize holds the value of the "actual_size" field.
	ActualSize *string `json:"actual_size,omitempty"`
	// Quality holds the value of the "quality" field.
	Quality *string `json:"quality,omitempty"`
	// ResponseFormat holds the value of the "response_format" field.
	ResponseFormat *string `json:"response_format,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash *string `json:"request_hash,omitempty"`
	// PromptHash holds the value of the "prompt_hash" field.
	PromptHash string `json:"prompt_hash,omitempty"`
	// PayloadObjectRef holds the value of the "payload_object_ref" field.
	PayloadObjectRef *string `json:"payload_object_ref,omitempty"`
	// ResultObjectRefs holds the value of the "result_object_refs" field.
	ResultObjectRefs []string `json:"result_object_refs,omitempty"`
	// BaseCost holds the value of the "base_cost" field.
	BaseCost float64 `json:"base_cost,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost float64 `json:"estimated_cost,omitempty"`
	// HeldCost holds the value of the "held_cost" field.
	HeldCost float64 `json:"held_cost,omitempty"`
	// SettledCost holds the value of the "settled_cost" field.
	SettledCost float64 `json:"settled_cost,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode *string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// ClaimVersion holds the value of the "claim_version" field.
	ClaimVersion int64 `json:"claim_version,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt *time.Time `json:"lease_expires_at,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt *time.Time `json:"next_attempt_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt *time.Time `json:"submitted_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt    *time.Time `json:"settled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageGenerationJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagegenerationjob.FieldResultObjectRefs:
			values[i] = new([]byte)
		case imagegenerationjob.FieldBaseCost, imagegenerationjob.FieldRateMultiplier, imagegenerationjob.FieldEstimatedCost, imagegenerationjob.FieldHeldCost, imagegenerationjob.FieldSettledCost:
			values[i] = new(sql.NullFloat64)
		case imagegenerationjob.FieldID, imagegenerationjob.FieldUserID, imagegenerationjob.FieldAPIKeyID, imagegenerationjob.FieldGroupID, imagegenerationjob.FieldSubscriptionID, imagegenerationjob.FieldAccountID, imagegenerationjob.FieldBillingType, imagegenerationjob.FieldAttemptCount, imagegenerationjob.FieldClaimVersion:
			values[i] = new(sql.NullInt64)
		case imagegenerationjob.FieldJobID, imagegenerationjob.FieldSource, imagegenerationjob.FieldOperation, imagegenerationjob.FieldStatus, imagegenerationjob.FieldPublicModel, imagegenerationjob.FieldDisplayName, imagegenerationjob.FieldUpstreamModel, imagegenerationjob.FieldRequestedSize, imagegenerationjob.FieldActualSize, imagegenerationjob.FieldQuality, imagegenerationjob.FieldResponseFormat, imagegenerationjob.FieldUpstreamTaskID, imagegenerationjob.FieldIdempotencyKey, imagegenerationjob.FieldRequestHash, imagegenerationjob.FieldPromptHash, imagegenerationjob.FieldPayloadObjectRef, imagegenerationjob.FieldErrorCode, imagegenerationjob.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case imagegenerationjob.FieldLeaseExpiresAt, imagegenerationjob.FieldNextAttemptAt, imagegenerationjob.FieldCreatedAt, imagegenerationjob.FieldUpdatedAt, imagegenerationjob.FieldSubmittedAt, imagegenerationjob.FieldCompletedAt, imagegenerationjob.FieldSettledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageGenerationJob fields.
func (_m *ImageGenerationJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagegenerationjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagegenerationjob.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case imagegenerationjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case imagegenerationjob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case imagegenerationjob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case imagegenerationjob.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case imagegenerationjob.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case imagegenerationjob.FieldBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = int8(value.Int64)
			}
		case imagegenerationjob.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case imagegenerationjob.FieldOperation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation", values[i])
			} else if value.Valid {
				_m.Operation = value.String
			}
		case imagegenerationjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case imagegenerationjob.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case imagegenerationjob.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case imagegenerationjob.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = new(string)
				*_m.UpstreamModel = value.String
			}
		case imagegenerationjob.FieldRequestedSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_size", values[i])
			} else if value.Valid {
				_m.RequestedSize = new(string)
				*_m.RequestedSize = value.String
			}
		case imagegenerationjob.FieldActualSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actual_size", values[i])
			} else if value.Valid {
				_m.ActualSize = new(string)
				*_m.ActualSize = value.String
			}
		case imagegenerationjob.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = new(string)
				*_m.Quality = value.String
			}
		case imagegenerationjob.FieldResponseFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_format", values[i])
			} else if value.Valid {
				_m.ResponseFormat = new(string)
				*_m.ResponseFormat = value.String
			}
		case imagegenerationjob.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case imagegenerationjob.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case imagegenerationjob.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = new(string)
				*_m.RequestHash = value.String
			}
		case imagegenerationjob.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = value.String
			}
		case imagegenerationjob.FieldPayloadObjectRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_object_ref", values[i])
			} else if value.Valid {
				_m.PayloadObjectRef = new(string)
				*_m.PayloadObjectRef = value.String
			}
		case imagegenerationjob.FieldResultObjectRefs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_object_refs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultObjectRefs); err != nil {
					return fmt.Errorf("unmarshal field result_object_refs: %w", err)
				}
			}
		case imagegenerationjob.FieldBaseCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_cost", values[i])
			} else if value.Valid {
				_m.BaseCost = value.Float64
			}
		case imagegenerationjob.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case imagegenerationjob.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.Float64
			}
		case imagegenerationjob.FieldHeldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field held_cost", values[i])
			} else if value.Valid {
				_m.HeldCost = value.Float64
			}
		case imagegenerationjob.FieldSettledCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settled_cost", values[i])
			} else if value.Valid {
				_m.SettledCost = value.Float64
			}
		case imagegenerationjob.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case imagegenerationjob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case imagegenerationjob.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case imagegenerationjob.FieldClaimVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field claim_version", values[i])
			} else if value.Valid {
				_m.ClaimVersion = value.Int64
			}
		case imagegenerationjob.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = new(time.Time)
				*_m.LeaseExpiresAt = value.Time
			}
		case imagegenerationjob.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = new(time.Time)
				*_m.NextAttemptAt = value.Time
			}
		case imagegenerationjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagegenerationjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagegenerationjob.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				_m.SubmittedAt = new(time.Time)
				*_m.SubmittedAt = value.Time
			}
		case imagegenerationjob.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case imagegenerationjob.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageGenerationJob.
// This includes values selected through modifiers, order, etc.
func (_m *ImageGenerationJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImageGenerationJob.
// Note that you need to call ImageGenerationJob.Unwrap() before calling this method if this ImageGenerationJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageGenerationJob) Update() *ImageGenerationJobUpdateOne {
	return NewImageGenerationJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageGenerationJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageGenerationJob) Unwrap() *ImageGenerationJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageGenerationJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageGenerationJob) String() string {
	var builder strings.Builder
	builder.WriteString("ImageGenerationJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingType))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("operation=")
	builder.WriteString(_m.Operation)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamModel; v != nil {
		builder.WriteString("upstream_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestedSize; v != nil {
		builder.WriteString("requested_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActualSize; v != nil {
		builder.WriteString("actual_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Quality; v != nil {
		builder.WriteString("quality=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponseFormat; v != nil {
		builder.WriteString("response_format=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestHash; v != nil {
		builder.WriteString("request_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("prompt_hash=")
	builder.WriteString(_m.PromptHash)
	builder.WriteString(", ")
	if v := _m.PayloadObjectRef; v != nil {
		builder.WriteString("payload_object_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("result_object_refs=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultObjectRefs))
	builder.WriteString(", ")
	builder.WriteString("base_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseCost))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedCost))
	builder.WriteString(", ")
	builder.WriteString("held_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.HeldCost))
	builder.WriteString(", ")
	builder.WriteString("settled_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettledCost))
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("claim_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaimVersion))
	builder.WriteString(", ")
	if v := _m.LeaseExpiresAt; v != nil {
		builder.WriteString("lease_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextAttemptAt; v != nil {
		builder.WriteString("next_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SubmittedAt; v != nil {
		builder.WriteString("submitted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImageGenerationJobs is a parsable slice of ImageGenerationJob.
type ImageGenerationJobs []*ImageGenerationJob
