// Code generated by ent, DO NOT EDIT.

package imagegenerationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imagegenerationjob type in the database.
	Label = "image_generation_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldBillingType holds the string denoting the billing_type field in the database.
	FieldBillingType = "billing_type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPublicModel holds the string denoting the public_model field in the database.
	FieldPublicModel = "public_model"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldRequestedSize holds the string denoting the requested_size field in the database.
	FieldRequestedSize = "requested_size"
	// FieldActualSize holds the string denoting the actual_size field in the database.
	FieldActualSize = "actual_size"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// FieldResponseFormat holds the string denoting the response_format field in the database.
	FieldResponseFormat = "response_format"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldPromptHash holds the string denoting the prompt_hash field in the database.
	FieldPromptHash = "prompt_hash"
	// FieldPayloadObjectRef holds the string denoting the payload_object_ref field in the database.
	FieldPayloadObjectRef = "payload_object_ref"
	// FieldResultObjectRefs holds the string denoting the result_object_refs field in the database.
	FieldResultObjectRefs = "result_object_refs"
	// FieldBaseCost holds the string denoting the base_cost field in the database.
	FieldBaseCost = "base_cost"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldEstimatedCost holds the string denoting the estimated_cost field in the database.
	FieldEstimatedCost = "estimated_cost"
	// FieldHeldCost holds the string denoting the held_cost field in the database.
	FieldHeldCost = "held_cost"
	// FieldSettledCost holds the string denoting the settled_cost field in the database.
	FieldSettledCost = "settled_cost"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldClaimVersion holds the string denoting the claim_version field in the database.
	FieldClaimVersion = "claim_version"
	// FieldLeaseExpiresAt holds the string denoting the lease_expires_at field in the database.
	FieldLeaseExpiresAt = "lease_expires_at"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// Table holds the table name of the imagegenerationjob in the database.
	Table = "image_generation_jobs"
)

// Columns holds all SQL columns for imagegenerationjob fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldSubscriptionID,
	FieldAccountID,
	FieldBillingType,
	FieldSource,
	FieldOperation,
	FieldStatus,
	FieldPublicModel,
	FieldDisplayName,
	FieldUpstreamModel,
	FieldRequestedSize,
	FieldActualSize,
	FieldQuality,
	FieldResponseFormat,
	FieldUpstreamTaskID,
	FieldIdempotencyKey,
	FieldRequestHash,
	FieldPromptHash,
	FieldPayloadObjectRef,
	FieldResultObjectRefs,
	FieldBaseCost,
	FieldRateMultiplier,
	FieldEstimatedCost,
	FieldHeldCost,
	FieldSettledCost,
	FieldErrorCode,
	FieldErrorMessage,
	FieldAttemptCount,
	FieldClaimVersion,
	FieldLeaseExpiresAt,
	FieldNextAttemptAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSubmittedAt,
	FieldCompletedAt,
	FieldSettledAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(string) error
	// DefaultBillingType holds the default value on creation for the "billing_type" field.
	DefaultBillingType int8
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	PublicModelValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// RequestedSizeValidator is a validator for the "requested_size" field. It is called by the builders before save.
	RequestedSizeValidator func(string) error
	// ActualSizeValidator is a validator for the "actual_size" field. It is called by the builders before save.
	ActualSizeValidator func(string) error
	// QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	QualityValidator func(string) error
	// ResponseFormatValidator is a validator for the "response_format" field. It is called by the builders before save.
	ResponseFormatValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// PromptHashValidator is a validator for the "prompt_hash" field. It is called by the builders before save.
	PromptHashValidator func(string) error
	// PayloadObjectRefValidator is a validator for the "payload_object_ref" field. It is called by the builders before save.
	PayloadObjectRefValidator func(string) error
	// DefaultResultObjectRefs holds the default value on creation for the "result_object_refs" field.
	DefaultResultObjectRefs []string
	// DefaultBaseCost holds the default value on creation for the "base_cost" field.
	DefaultBaseCost float64
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// DefaultEstimatedCost holds the default value on creation for the "estimated_cost" field.
	DefaultEstimatedCost float64
	// DefaultHeldCost holds the default value on creation for the "held_cost" field.
	DefaultHeldCost float64
	// DefaultSettledCost holds the default value on creation for the "settled_cost" field.
	DefaultSettledCost float64
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultClaimVersion holds the default value on creation for the "claim_version" field.
	DefaultClaimVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImageGenerationJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByBillingType orders the results by the billing_type field.
func ByBillingType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingType, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPublicModel orders the results by the public_model field.
func ByPublicModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicModel, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByRequestedSize orders the results by the requested_size field.
func ByRequestedSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedSize, opts...).ToFunc()
}

// ByActualSize orders the results by the actual_size field.
func ByActualSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualSize, opts...).ToFunc()
}

// ByQuality orders the results by the quality field.
func ByQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuality, opts...).ToFunc()
}

// ByResponseFormat orders the results by the response_format field.
func ByResponseFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseFormat, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByPromptHash orders the results by the prompt_hash field.
func ByPromptHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromptHash, opts...).ToFunc()
}

// ByPayloadObjectRef orders the results by the payload_object_ref field.
func ByPayloadObjectRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadObjectRef, opts...).ToFunc()
}

// ByBaseCost orders the results by the base_cost field.
func ByBaseCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseCost, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// ByEstimatedCost orders the results by the estimated_cost field.
func ByEstimatedCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedCost, opts...).ToFunc()
}

// ByHeldCost orders the results by the held_cost field.
func ByHeldCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeldCost, opts...).ToFunc()
}

// BySettledCost orders the results by the settled_cost field.
func BySettledCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledCost, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByClaimVersion orders the results by the claim_version field.
func ByClaimVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimVersion, opts...).ToFunc()
}

// ByLeaseExpiresAt orders the results by the lease_expires_at field.
func ByLeaseExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeaseExpiresAt, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}
